name: Convert LaTeX to PDF file

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        ref: dev
    - name: Convert pdf file
      run:  docker run --rm -t --user="$(id -u):$(id -g)" --net=none -v "$(pwd):/tmp" kreal321/latex:amd64 latexmk -outdir=/tmp -f -pdf Kezhen_Xu_Resume.tex
      
    - name: Convert PDF to PNG
      run: sudo apt-get install -y poppler-utils && pdftoppm -png Kezhen_Xu_Resume.pdf Kezhen_Xu_Resume

    - name: Upload PDF and PNG as artifacts
      uses: actions/upload-artifact@v4
      with:
        name: resume_files
        path: |
          Kezhen_Xu_Resume.pdf
          Kezhen_Xu_Resume-*.png

    - name: File cleanup
      run: find . -name "*.fdb_latexmk" -type f -delete && mv -f Kezhen_Xu_Resume-1.png Kezhen_Xu_Resume.png

    - name: Publish Build to GitHub
      uses: mikeal/publish-to-github-action@master
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH_NAME: 'main'

